---
platforms:
  - name: oraclelinux-7
    groups:
      - nomad_instances
    image: dokken/oraclelinux-7
    dockerfile: ../_shared/Dockerfile.j2
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    command: /usr/lib/systemd/systemd
