---
# ansible.builtin.file: selinux.yml - SELinux tasks for Nomad

# SELinux disrupts LXC (shrug)

- name: Disable SELinux for Docker Driver
  selinux:
    state: disabled
  when: nomad_docker_enable == "true"
