---
# ansible.builtin.file: user_group.yml - User and group settings

- name: Add Nomad group
  group:
    name: "{{ nomad_group }}"
    state: present
  when:
    - nomad_manage_group | bool

- name: Add Nomad user
  user:
    name: "{{ nomad_user }}"
    comment: "Nomad user"
    group: "{{ nomad_group }}"
    system: yes
  when:
    - nomad_manage_user | bool
