---
# File: site.yml - Example nomad site playbook

- name: Installing Nomad
  hosts: nomad_instances
  become: yes
  become_user: root

  tasks:
    - name: nomad role
      include_role:
        name: ansible-community.nomad

    - name: Start nomad
      service: name=nomad state=started enabled=yes
