---
- name: Converge
  hosts: all
  roles:
    - role: ansible-nomad

  vars:
    # Force SysVinit, since systemd won't work in a Docker container
    ansible_service_mgr: "sysvinit"
    # TODO: Probably we need to install syslog-ng/rsyslog first
    nomad_syslog_enable: False
