---
platforms:
  - name: debian-10
    groups:
      - nomad_instances
    image: dokken/debian-10
    dockerfile: ../_shared/Dockerfile.j2
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    command: /bin/systemd
